name: Build and Push Docker Image

on:
  workflow_run:
    workflows:
      - Fix Code Style
    types:
      - completed

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Extract Repository Name
        id: repo-name
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -f docker/prod/Dockerfile -t ${{ vars.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:latest .
      - name: Push Docker Image
        run: |
          docker push ${{ vars.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:latest
